### ISSUE TITLE
Retrieve version of the app

### ISSUE THREAD

**Issue by SRARS** [rossmartin/app-store-scraper-reviews#1]
I want to suggest also retrieve the current version of the app

**Comment by rossmartin** [comment]
Unfortunately that isn't possible using this module. The API/technique that this uses is mainly for retrieving _all_ reviews for a given app.

I recommend using [app-store-scraper](https://github.com/facundoolano/app-store-scraper) to get the current version of a given app. Specifically the `app` method it provides.
