### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by sabatale** [rossmartin/app-store-scraper-reviews#2]
Would you have an example for proxy support (undici, proxy-agent, etc.) with the library?

Currently, we're unable to get any reviews and this may be due to proxy issues crashing the process along the way.

Your example "1271273970" works fine, but not "570060128" (Duolingo) with a 1000 reviews target:

```
FetchError: request to https://amp-api.apps.apple.com/v1/catalog/us/apps/{appId}/reviews?l=en-GB&offset=0&limit=20&platform=web&additionalPlatforms=appletv%2Cipad%2Ciphone%2Cmac failed, reason:
    at ClientRequest.<anonymous> (...\node_modules\node-fetch\lib\index.js:1505:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

**Comment by rossmartin** [comment]
I don't have any examples using a proxy and haven't tried it. It should be possible though using the `fetchReviews` function here - https://github.com/rossmartin/app-store-scraper-reviews/blob/6703c06fdf06ecf50fc083a3cd0e77972d990ac7/src/api/fetchReviews.ts#L26

Have you tried using the optional `sleep` parameter on the `getReviews` function? It looks like from your example it might be failing on the first request but I'm not sure. If it isn't then increasing `sleep` can help prevent subsequent requests from being blocked.

Here is an untested example that AI cooked up using `https-proxy-agent` and altering the `fetchReviews` function:

```ts
import { HttpsProxyAgent } from 'https-proxy-agent';

export async function fetchReviews() {
  // ...

  // Define your proxy URL and port
  const proxyUrl = 'http://your-proxy-url:your-proxy-port';

  // Create an instance of HttpsProxyAgent with your proxy URL
  const proxyAgent = new HttpsProxyAgent(proxyUrl);
  
  // Pass the agent option with the proxy agent to the fetch call
  const fetchResult = await fetch(`${requestUrl}?${params.toString()}`, {
    agent: proxyAgent, // Use the proxy agent
    // ...
  });
  
  return fetchResult.json();
});
```

Can roast me on the "untested example cooked up by AI" 😆
